[package]
name = "antikythera_rs"
version = "0.0.1"
edition = "2021"
authors = ["Jamie Callan"]

[dependencies]
reqwest = { version = "0.12.4", features = ["json"] }
tokio = { version = "1", features = ["full"] }
serde_json = "1.0"
anyhow = "1.0"
